name: MBLogin
main: cc.venja.minebbs.login.LoginMain
version: 1.0.0
author: Kazi-VE
api-version: 1.13

commands:
  register:
    description: MBLogin注册指令
  login:
    description: MBLogin登录指令
  autologin:
    description: MBLogin启用/关闭同IP自动登录
