name: MBBattle
main: cc.venja.minebbs.battle.BattleMain
version: 1.0.0
author: Kazi-VE
api-version: 1.13

softdepend:
  - MBLogin
  - MBRobot

commands:
  generate-stronghold:
    description: 手动生成指定据点
  gamestatus-change:
    description: 修改游戏状态
  arena:
    description: 墙控制